### ISSUE TITLE
Plugin Outdated?

### ISSUE THREAD

**Issue by EmptyStreets** [lukeholder/craft-geo#4]
Hello,

Just installed your plugin on a 2.5+ version and it only shows the country information, ip address and some other values, however the main fields are empty (like state, state code etc). Tried several times, different browsers and locations (VPN).

Is there a chance you take a look at this issue or update the plugin soon?

Thank you.

**Comment by Coalescent** [comment]
It does nothing for me on the latest Craft (2.6.x). I can't get any data. I assume this has been abandoned.

**Comment by cavellblood** [comment]
@lukeholder, @Coalescent, and @EmptyStreets: It appears that the [`config.php`](https://github.com/lukeholder/craft-geo/blob/master/geo/config.php) file has a default IP address set to an address in Costa Rica(?) that was returning an error on http://geoip.nekudo.com. I found that if you copy the [`geo.php`](https://github.com/lukeholder/craft-geo/blob/master/geo-examples/geo.php) file from the [`geo-examples`](https://github.com/lukeholder/craft-geo/tree/master/geo-examples) folder and follow the instructions on where to put it (in the `craft/config` folder) that it will work as expected.

Perhaps the `defaultIp` config variable should be set to `8.8.8.8` in the plugin so it doesn't silently error.

Also, if you do try this you'll need to clear your data caches from the Craft control panel while testing otherwise you won't see an update for 12 hours.

**Comment by lukeholder** [comment]
No longer maintained. Will not be upgraded for Craft 3.

Craft 3 alternatives include:

    https://plugins.craftcms.com/geo-cookie
    https://plugins.craftcms.com/geomate
    https://plugins.craftcms.com/country-detect
